loaders/mysql.go, loaders/mysql_test.go
- Special case MySQL `bit(1)` to map to Go `bool`
- Other precisions of MySQL `bit` type map to `uint8`, `uint16`, `uint32`, or `uint64`
- Added test for `bit` type conversions
I also tested this against the following table in MySQL:
```
CREATE TABLE `dummy` (
`iddummy` int(11) NOT NULL AUTO_INCREMENT,
`dummycol` bit(1) NOT NULL,
`dummycol2` bit(8) NOT NULL,
`dummycol3` bit(9) NOT NULL,
`dummycol5` bit(16) NOT NULL,
`dummycol1` bit(17) NOT NULL,
`dummycol4` bit(32) NOT NULL,
`dummycol6` bit(33) NOT NULL,
`dummycol7` bit(64) NOT NULL,
`dummycol8` bit(64) DEFAULT NULL,
`dummycol9` bit(1) DEFAULT NULL,
PRIMARY KEY (`iddummy`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
```
One possible issue is that if a type is nullable, it maps to `sql.NullInt64`, so the high bit is not usable.
=> fix MySQL bit type conversion to Go type

README.md, internal/argtype.go, internal/loader.go
cc @knq
Let me know what you think -- this should be useful for supporting DB-managed fields.
I thought about using labeled breaks but just having an `ignore` value seems a smidge cleaner to me.
Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>
=> Add support for ignoring fields

loaders/mysql.go
This addresses an issue raised in #67.  The MySQL time type is not supported for mapping in the MySQL Go driver to a time.Time object because it doesn't have a one-to-one relation with any type in Go (closest is a duration).  The best thing to do is to just map it as a string and that prevents an error in the query.  The consuming application can then map the type to a time in the user code by using the Time.Parse(layout, valuestring) feature.
=> Change mapping of MySQL time type to Go string type.

gen.sh, loaders/oracle.go, models/column.xo.go
Retrieve precision and scale in the type name,
and use it to decide between int64, flota64 and string for NUMBER.
=> oracle: use precision and scale, to use it to decide type

main.go
Right now exec-ing goimports ignores any error output. This makes debugging really difficult when you have some generated template error that goimports doesn't like.
This PR dumps stderr/stdout of the goimports exec if goimports fails.
=> Log goimport errors

templates/gotpl/schema/typedef.xo.go.tpl
This changes the generated code for the Insert function, when the
primary key is manually handled. This code would always fail as no row
is returned in an insert with a manual primary key. This change instead
uses Exec, and does not scan anything back.
=> Fixing a minor issue with the Go typedef template

README.md
The note was outdated.
"xo dump" is by default only creating templates for the Go language
instead of for all languages.
Therefore there are by default also no templates for other languages
that can be deleted.
=> readme: update note about templ languages created by xo dump

templates/gotpl/schema/proc.xo.go.tpl
Otherwise, you generate `// runlogf(sqlstr)`
=> fix logf in stored procedure template

templates/gotpl/funcs.go.tpl
The generated Update SQL statement for tables that had composite primary
keys were invalid.
The columns in the WHERE clause where concatenated with an ", " instead
of " AND ".
In the generated where clause the primary keys are concatenated with an , instead of AND.
This fixes https://github.com/xo/xo/issues/325
=> go template: fix: update statement for composite primary keys is broken

templates/gotpl/funcs.go.tpl, templates/gotpl/gotpl.go
Fix typo on documentations and complete `sqlstr_index` documentations in `templates/gotpl` package.
=> templates/gotpl: fix typo on documentations

gen.sh, models/enum.xo.go, models/enumvalue.xo.go
Currently, the query is generating tons of irrelevant results since missing the join criteria for `pg_class` table, thus introducing the issue #339.
This commit adds the correct join criteria between the `pg_class` table and `pg_type` table to fix it.
=> fix: Add correct join clause for postgres enum queries

README.md
The readme was outdated.
There was no schema description and the xo command was failing.
Fixed to add schema and run correctly
=> readme: update mysql

README.md
Since Go 1.16, which is also the documented min. version, the
recommended way to build and install applications is "go install"[^1].
Update the readme accordingly.
[^1]: https://go.dev/doc/go1.16#go-command
=> readme: update installation documentation

cmd/query.go
This makes xo not panic when `-B` is not provided.
=> Make comments an empty slice when strip is not enabled

templates/go/go.go
SSIA
I tried to run `xo dump` and customized the template. And then found a misspelling.
```
$ go install github.com/xo/xo@latest
$ go install github.com/client9/misspell/cmd/misspell@latest
$ xo dump -t go .
$ misspell .
go.go:2695:57: "columsn" is a misspelling of "columns"
```
=> fix: Fix typo in Go template

README.md
According to investigations in the issue [367](https://github.com/xo/xo/issues/367), xo/xo requires 1.19+ go version.
=> #367 updated required Go version in README.md

cmd/schema.go, gen.sh, models/column.xo.go, templates/go/go.go, types/types.go
Hello, here's my attempt to implement the issue described there:
https://github.com/xo/xo/issues/374
I've made changes only for PostgreSQL and MySQL
Short list of the changes:
1. gen.sh - enrich SQL query to get table's column's comment from pg_description table
2. types/types.go - added Comment field to the Field struct
3. cmd/schema.go - passed new value from query result to xo.Field
4. models/column.xo.go - generated stuff
5. templates/go/go.go - changes in the standard templates
=> #374 provide a comment of the column into structure used in Templates

templates/go/schema.xo.go.tpl
Database : Postgres
Using custom enums of the string variety causes a Scan error as it is only looking for the type `[]byte` 
Here is an example of a custom type using strings:
```sql
CREATE TYPE address_kind AS ENUM ('billing', 'shipping', 'mailing');
```
An example of using the custom `address_kind` in a table:
```sql
CREATE TABLE customer_address (
id bigserial PRIMARY KEY,
store_id bigint NOT NULL,
customer_id bigint NOT NULL,
kind address_kind NOT NULL,
is_default boolean DEFAULT FALSE NOT NULL,
street character varying NOT NULL,
apt_suite character varying NULL,
city character varying NOT NULL,
state_province character varying NOT NULL,
country character varying NOT NULL,
postal_code character varying NOT NULL,
created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT …
```
=> Adding string check to custom enums for Scan interface

templates/templates.go
- Ensure windows paths have forward slash.
Fix suggested by [r-lazzaro](https://github.com/pieter-lazzaro).
=> Fix Issue #387 - Run xo fails on Windows OS

_examples/booktest/sqlite3/db.xo.go, templates/go/db.xo.go.tpl
JSON (un)marshaling `Time` doesn't work because the `Time.time` field is unexported. This adds the `MarshalJSON` and `UnmarshalJSON` methods to fix this.
=> Add JSON methods to sqlite Time type

README.md
- Fix arguments for `xo query` in README
- `-T` requires a type name instead of `-2`
=> Fix arguments for `xo query` in README

gen.sh, models/foreignkey.xo.go
Path to fix the issue [#396](https://github.com/xo/xo/issues/396).
@kenshaw please, take a look. 
I hope it would be useful and I fixed all files needed.
1. I made changes in `gen.sh`
2. `sh gen.sh models`
3. restored all the code for other DBs (I have Postgres only) that was erased by `gen.sh`
4. build `xo` binary and checked that it generates code without issue
=> #396 changes in gen.sh and models

gen.sh, models/table.xo.go, templates/go/go.go
For postgresql, comments for tables are not extracted from the database. In addition, the default template does not use information about comments.
=> fix psql comments

cmd/schema.go
Fix generation of code for postresql multiline comments.
Example of sql schema:
Bugged generation:
=> Fix postresql multiline comments
